spring:
  jpa:
    properties:
      hibernate:
        format_sql: true

logging.level:
  org.hibernate.SQL: debug

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true