INSERT INTO education (name, priority) VALUES ('고졸', 1)
INSERT INTO education (name, priority) VALUES ('대재', 2)
INSERT INTO education (name, priority) VALUES ('대졸', 3)
INSERT INTO education (name, priority) VALUES ('휴학', 4)
INSERT INTO education (name, priority) VALUES ('석재', 5)
INSERT INTO education (name, priority) VALUES ('석졸', 6)

INSERT INTO category (name) VALUES ('보병')
INSERT INTO category (name) VALUES ('정보')
INSERT INTO category (name) VALUES ('공병')
INSERT INTO category (name) VALUES ('정보통신')
INSERT INTO category (name) VALUES ('항공')
INSERT INTO category (name) VALUES ('화학')
INSERT INTO category (name) VALUES ('수송')
INSERT INTO category (name) VALUES ('인사')
INSERT INTO category (name) VALUES ('군사경찰')
INSERT INTO category (name) VALUES ('재정')
INSERT INTO category (name) VALUES ('공보정훈')
INSERT INTO category (name) VALUES ('군악')
INSERT INTO category (name) VALUES ('의무')
INSERT INTO category (name) VALUES ('군종')

INSERT INTO branch (name, category_id) VALUES ('특공병', 1)
INSERT INTO branch (name, category_id) VALUES ('체육학조교병', 1)
INSERT INTO branch (name, category_id) VALUES ('유해발굴기록병', 1)
INSERT INTO branch (name, category_id) VALUES ('군마조교병', 1)
INSERT INTO branch (name, category_id) VALUES ('의장병', 1)
INSERT INTO branch (name, category_id) VALUES ('훈련소조교병', 1)
INSERT INTO branch (name, category_id) VALUES ('특전병', 1)
INSERT INTO branch (name, category_id) VALUES ('방송병', 2)
INSERT INTO branch (name, category_id) VALUES ('신호정보병', 2)
INSERT INTO branch (name, category_id) VALUES ('탐지분석병', 2)
INSERT INTO branch (name, category_id) VALUES ('드론운용및정비병', 2)
INSERT INTO branch (name, category_id) VALUES ('지형자료관리병', 3)
INSERT INTO branch (name, category_id) VALUES ('정보보호병', 4)
INSERT INTO branch (name, category_id) VALUES ('SW개발병', 4)
INSERT INTO branch (name, category_id) VALUES ('대형기동헬기정비병', 5)
INSERT INTO branch (name, category_id) VALUES ('화생방시험병', 6)
INSERT INTO branch (name, category_id) VALUES ('방사능분석연구보조병', 6)
INSERT INTO branch (name, category_id) VALUES ('생물학시험병', 6)
INSERT INTO branch (name, category_id) VALUES ('대형버스운전병', 7)
INSERT INTO branch (name, category_id) VALUES ('구급차량운전병', 7)
INSERT INTO branch (name, category_id) VALUES ('속기병', 8)
INSERT INTO branch (name, category_id) VALUES ('지식재산관리병', 8)
INSERT INTO branch (name, category_id) VALUES ('특임군사경찰', 9)
INSERT INTO branch (name, category_id) VALUES ('MC군사경찰', 9)
INSERT INTO branch (name, category_id) VALUES ('33경호병', 9)
INSERT INTO branch (name, category_id) VALUES ('회계원가비용분석병', 10)
INSERT INTO branch (name, category_id) VALUES ('영상콘텐츠디자이너', 11)
INSERT INTO branch (name, category_id) VALUES ('그래픽디자이너', 11)
INSERT INTO branch (name, category_id) VALUES ('사진콘텐츠디자이너', 11)
INSERT INTO branch (name, category_id) VALUES ('군사과학기술병', 11)
INSERT INTO branch (name, category_id) VALUES ('목관악기', 12)
INSERT INTO branch (name, category_id) VALUES ('금관악기', 12)
INSERT INTO branch (name, category_id) VALUES ('타악기', 12)
INSERT INTO branch (name, category_id) VALUES ('현악기', 12)
INSERT INTO branch (name, category_id) VALUES ('국악', 12)
INSERT INTO branch (name, category_id) VALUES ('실용음악', 12)
INSERT INTO branch (name, category_id) VALUES ('유해발굴감식병', 13)
INSERT INTO branch (name, category_id) VALUES ('기독교군종병', 14)
INSERT INTO branch (name, category_id) VALUES ('천주교군종병', 14)
INSERT INTO branch (name, category_id) VALUES ('불교군종병', 14)